---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  ports:
    - name: gitlab-ui
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
    - name: gitlab-ssh
      port: 22
      protocol: TCP
      targetPort: 22
      nodePort: 30022
  selector:
    app: gitlab
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitlab
        tier: frontend
    spec:
      containers:
        - image: gitlab/gitlab-ce:10.3.3-ce.0
          name: gitlab
          #command: ['sh', '-c', 'apt-get update && apt-get install -yq --no-install-recommends sendmail']
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                postgresql['enable'] = false
                gitlab_rails['db_username'] = "gitlab"
                gitlab_rails['db_password'] = "gitlab"
                gitlab_rails['db_host'] = "postgresql"
                gitlab_rails['db_port'] = "5432"
                gitlab_rails['db_database'] = "gitlabhq_production"
                gitlab_rails['db_adapter'] = 'postgresql'
                gitlab_rails['db_encoding'] = 'utf8'
                redis['enable'] = false
                gitlab_rails['redis_host'] = 'redis'
                gitlab_rails['redis_port'] = '6379'
                gitlab_rails['gitlab_shell_ssh_port'] = 30022
                external_url 'http://gitlab.mycluster.uk-south.containers.mybluemix.net'
                git_data_dirs({"default" => {"path" => "/home/git/data/git-data"}})
                gitlab_rails['shared_path'] = '/home/git/data/shared'
                gitlab_rails['uploads_directory'] = '/home/git/data/uploads'
                nginx['client_max_body_size'] = '200m'
                #gitlab_rails['gitlab_email_enabled'] = true
                #gitlab_rails['gitlab_email_from'] = 'noreply@gitlab.mycluster.uk-south.containers.mybluemix.net'
                #gitlab_rails['gitlab_email_display_name'] = 'Innovation Factory - Gitlab'
                #gitlab_rails['gitlab_email_reply_to'] = 'noreply@gitlab.mycluster.uk-south.containers.mybluemix.net'
                #gitlab_rails['gitlab_email_subject_suffix'] = '[GitLab]'
          ports:
            - containerPort: 30080
              name: gitlab
          volumeMounts:
            - name: gitlab
              mountPath: /home/git/data:rw
      volumes:
        - name: gitlab
          persistentVolumeClaim:
            claimName: gitlab-data-claim
